import Foundation

public extension Notification.Name {
    static let lexPadToggleFind = Notification.Name("LexPadToggleFind")
    static let lexPadToggleReplace = Notification.Name("LexPadToggleReplace")
    static let lexPadGoToLine = Notification.Name("LexPadGoToLine")
    static let lexPadToggleWordWrap = Notification.Name("LexPadToggleWordWrap")
    static let lexPadDuplicateLine = Notification.Name("LexPadDuplicateLine")
    static let lexPadSortLinesAsc = Notification.Name("LexPadSortLinesAsc")
    static let lexPadSortLinesDesc = Notification.Name("LexPadSortLinesDesc")
    static let lexPadRemoveDupLines = Notification.Name("LexPadRemoveDupLines")
    static let lexPadTrimTrailing = Notification.Name("LexPadTrimTrailing")
    static let lexPadTrimLeading = Notification.Name("LexPadTrimLeading")
    static let lexPadRemoveEmptyLines = Notification.Name("LexPadRemoveEmptyLines")
    static let lexPadJoinLines = Notification.Name("LexPadJoinLines")
    static let lexPadReverseLines = Notification.Name("LexPadReverseLines")
    static let lexPadMoveLineUp = Notification.Name("LexPadMoveLineUp")
    static let lexPadMoveLineDown = Notification.Name("LexPadMoveLineDown")
    static let lexPadUpperCase = Notification.Name("LexPadUpperCase")
    static let lexPadLowerCase = Notification.Name("LexPadLowerCase")
    static let lexPadProperCase = Notification.Name("LexPadProperCase")
    static let lexPadInvertCase = Notification.Name("LexPadInvertCase")
    static let lexPadTabsToSpaces = Notification.Name("LexPadTabsToSpaces")
    static let lexPadSpacesToTabs = Notification.Name("LexPadSpacesToTabs")
    static let lexPadConvertEOLToLF = Notification.Name("LexPadConvertEOLToLF")
    static let lexPadConvertEOLToCRLF = Notification.Name("LexPadConvertEOLToCRLF")
    static let lexPadConvertEOLToCR = Notification.Name("LexPadConvertEOLToCR")
    static let lexPadFindInFiles = Notification.Name("LexPadFindInFiles")
    static let lexPadCompareFiles = Notification.Name("LexPadCompareFiles")
    static let lexPadFoldAll = Notification.Name("LexPadFoldAll")
    static let lexPadUnfoldAll = Notification.Name("LexPadUnfoldAll")
    static let lexPadShowPreferences = Notification.Name("LexPadShowPreferences")
    static let lexPadCommandPalette = Notification.Name("LexPadCommandPalette")
    static let lexPadQuickOpen = Notification.Name("LexPadQuickOpen")
    static let lexPadStartMacroRecording = Notification.Name("LexPadStartMacroRecording")
    static let lexPadStopMacroRecording = Notification.Name("LexPadStopMacroRecording")
    static let lexPadEditorAction = Notification.Name("LexPadEditorAction")
    static let lexPadNewTab = Notification.Name("LexPadNewTab")
    static let lexPadToggleOverwrite = Notification.Name("LexPadToggleOverwrite")
    static let lexPadToggleBookmark = Notification.Name("LexPadToggleBookmark")
    static let lexPadNextBookmark = Notification.Name("LexPadNextBookmark")
    static let lexPadPreviousBookmark = Notification.Name("LexPadPreviousBookmark")
    static let lexPadClearBookmarks = Notification.Name("LexPadClearBookmarks")
    static let lexPadBookmarkAllMatches = Notification.Name("LexPadBookmarkAllMatches")
    static let lexPadToggleComment = Notification.Name("LexPadToggleComment")
    static let lexPadToggleSyncScroll = Notification.Name("LexPadToggleSyncScroll")
    static let lexPadReplaceInFiles = Notification.Name("LexPadReplaceInFiles")
    static let lexPadReloadFile = Notification.Name("LexPadReloadFile")
    static let lexPadSplitHorizontal = Notification.Name("LexPadSplitHorizontal")
    static let lexPadSplitVertical = Notification.Name("LexPadSplitVertical")
    static let lexPadCloneDocument = Notification.Name("LexPadCloneDocument")
    static let lexPadCloseSplit = Notification.Name("LexPadCloseSplit")
    static let lexPadToggleWorkspace = Notification.Name("LexPadToggleWorkspace")
    static let lexPadToggleFunctionList = Notification.Name("LexPadToggleFunctionList")
    static let lexPadOpenFolder = Notification.Name("LexPadOpenFolder")
    static let lexPadIncrementalSearch = Notification.Name("LexPadIncrementalSearch")
    static let lexPadColumnEditor = Notification.Name("LexPadColumnEditor")
    static let lexPadSaveProject = Notification.Name("LexPadSaveProject")
    static let lexPadOpenProject = Notification.Name("LexPadOpenProject")
    static let lexPadToggleGitPanel = Notification.Name("LexPadToggleGitPanel")
    static let lexPadPluginManager = Notification.Name("LexPadPluginManager")
    static let lexPadShowStyleConfigurator = Notification.Name("LexPadShowStyleConfigurator")
    static let lexPadSave = Notification.Name("LexPadSave")
    static let lexPadToggleDocumentList = Notification.Name("LexPadToggleDocumentList")
    static let lexPadToggleDocumentMap = Notification.Name("LexPadToggleDocumentMap")
    static let lexPadSetMarkStyle = Notification.Name("LexPadSetMarkStyle")
    static let lexPadClearMarkStyle = Notification.Name("LexPadClearMarkStyle")
    static let lexPadMoveToOtherView = Notification.Name("LexPadMoveToOtherView")
    static let lexPadGroupTabsByFolder = Notification.Name("LexPadGroupTabsByFolder")
    static let lexPadNewTabGroup = Notification.Name("LexPadNewTabGroup")
    static let lexPadSelectNextOccurrence = Notification.Name("LexPadSelectNextOccurrence")
    static let lexPadToggleSnippets = Notification.Name("LexPadToggleSnippets")
    static let lexPadInsertSnippet = Notification.Name("LexPadInsertSnippet")
    static let lexPadOpenPendingFiles = Notification.Name("LexPadOpenPendingFiles")
    static let lexPadTriggerCompletion = Notification.Name("LexPadTriggerCompletion")
    static let lexPadOpenUDLEditor = Notification.Name("LexPadOpenUDLEditor")
    static let lexPadSplitLines = Notification.Name("LexPadSplitLines")
    static let lexPadToggleBlockComment = Notification.Name("LexPadToggleBlockComment")
    static let lexPadPrint = Notification.Name("LexPadPrint")
    static let lexPadToggleCharacterPanel = Notification.Name("LexPadToggleCharacterPanel")
    static let lexPadToggleHexView = Notification.Name("LexPadToggleHexView")
    static let lexPadToggleProjectPanel = Notification.Name("LexPadToggleProjectPanel")
    static let lexPadFindInProject = Notification.Name("LexPadFindInProject")
    static let lexPadSetEncoding = Notification.Name("LexPadSetEncoding")
    static let lexPadBeginSelect = Notification.Name("LexPadBeginSelect")
    static let lexPadEndSelect = Notification.Name("LexPadEndSelect")
    static let lexPadToggleVirtualSpace = Notification.Name("LexPadToggleVirtualSpace")
    static let lexPadRunPlugin = Notification.Name("LexPadRunPlugin")
    static let lexPadToggleRecentFiles = Notification.Name("LexPadToggleRecentFiles")
    static let lexPadClearRecentFiles = Notification.Name("LexPadClearRecentFiles")
    static let lexPadSaveSession = Notification.Name("LexPadSaveSession")
    static let lexPadGoToLineSelection = Notification.Name("LexPadGoToLineSelection")
    static let lexPadNewWindow = Notification.Name("LexPadNewWindow")
    static let lexPadDuplicateTab = Notification.Name("LexPadDuplicateTab")
    static let lexPadToggleReadOnly = Notification.Name("LexPadToggleReadOnly")
    static let lexPadTogglePinTab = Notification.Name("LexPadTogglePinTab")
    static let lexPadFormatJSON = Notification.Name("LexPadFormatJSON")
    static let lexPadFormatXML = Notification.Name("LexPadFormatXML")
    static let lexPadShowHelp = Notification.Name("LexPadShowHelp")
    static let lexPadShowAbout = Notification.Name("LexPadShowAbout")
}

/// Posts a macro-recordable command notification.
public func postMacroCommand(_ name: Notification.Name) {
    NotificationCenter.default.post(name: name, object: nil)
    NotificationCenter.default.post(
        name: .lexPadMacroCommand,
        object: nil,
        userInfo: ["command": name.rawValue]
    )
}
